### ISSUE TITLE
Any chance to setup which directories to index to enable goto ?

### ISSUE THREAD

**Issue by silver-mx** [v3ss0n/goto#68]
First of all, nice job with the plugin. I have a medium size project, and takes a long time to create the index. In the project we have lots of config files for which I do not need "goto". It is basically only the classes that need the functionality, and they are not too many. It would be nice to tell which folders you should include in the index, sound like plausible?

**Comment by acusti** [comment]
It might be worth looking into reusing the logic from find-and-replace’s Find in Project command, so that we could specify a paths pattern and use that to determine what to index. Could also help make the plugin more generally useful without other performance optimizations.

Reference:

* see [find-and-replace’s usage](https://github.com/atom/find-and-replace/blob/master/lib/project/results-model.coffee#L118) of `atom.workspace.scan`
* and the definition of [`atom.workspace.scan`](https://github.com/atom/atom/blob/master/src/workspace.coffee#L815)
* fuzzy-finder has a [`PathLoader` class](https://github.com/atom/fuzzy-finder/blob/master/lib/load-paths-handler.coffee) that accepts an `ignoredNames` parameter, which is an array of filenames that should be skipped. It also has a boolean that lets you specify whether or not to follow symlinks, which is another issue in this project

**Comment by acusti** [comment]
You can do this using the “More ignored names” option in the plugin settings. You can either specify paths of filename globs to ignore, like `*.config.json`, or directories, like `config` (most efficient, because the file traversal will skip that part of your project’s directory tree entirely). You could also try a negation to ensure that only a particular directory is indexed. So if you only wanted to index `models`, you could try using `!models` as the “More ignored names” option value, though I haven’t verified that that will work.
